name: Check IPs in AbuseIPDB

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta el script todos los d칤as a medianoche UTC
  workflow_dispatch:  # Permite ejecuci칩n manual desde GitHub Actions

jobs:
  check_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests PyGithub

      - name: Crear archivo si no existe
        run: |
          touch filtered_ips.txt  # Crea el archivo si no existe
          git add filtered_ips.txt  # Asegura que Git lo rastree

      - name: Ejecutar script de verificaci칩n
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ABUSEIPDB_API_KEY_1: ${{ secrets.ABUSEIPDB_API_KEY_1 }}
          ABUSEIPDB_API_KEY_2: ${{ secrets.ABUSEIPDB_API_KEY_2 }}
          ABUSEIPDB_API_KEY_3: ${{ secrets.ABUSEIPDB_API_KEY_3 }}
          ABUSEIPDB_API_KEY_4: ${{ secrets.ABUSEIPDB_API_KEY_4 }}
        run: python check_ip.py

      - name: Subir cambios si hay modificaciones
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git pull --rebase  # Trae los 칰ltimos cambios antes de hacer commit          
          git add -A  # Asegura que se agreguen todos los archivos

          # Verificar si hay cambios antes de hacer commit
          git diff --staged --quiet || (
            git commit -m "游댃 Actualizaci칩n autom치tica de IPs filtradas"
            git push
          )
